from django.urls import path
from . import views
# from .views import MemberFileView

urlpatterns = [
    path('',
         views.members_list,
         name='members_list'),
    path('TI_Management_app/members_table_list',
         views.members_table_list,
         name='members_table_list'),
    path('TI_Management_app/<int:pk>/',
         views.member_detail,
         name='member_detail'),
    path('TI_Management_app/new/',
         views.member_new,
         name='member_new'),
    path('TI_Management_app/memberFunction/',
         views.member_function_add,
         name='member_function_add'),
    path('TI_Management_app/memberOccupation/',
         views.member_occupation_add,
         name='member_occupation_add'),
    path('TI_Management_app/<int:pk>/edit/',
         views.member_edit,
         name='member_edit'),
    path('TI_Management_app/<int:pk>/editCard/',
         views.member_card_edit,
         name='member_card_edit'),
    path('TI_Management_app/<int:pk>/memberDeactivate/',
         views.member_deactivate,
         name='member_deactivate'),
    path('TI_Management_app/<int:pk>/editFile/',
         views.member_file_edit,
         name='member_file_edit'),
    path('TI_Management_app/<int:pk>/deleteFile/<int:pk1>/',
         views.member_file_delete,
         name='member_file_delete'),
    path('TI_Management_app/<int:pk>/editLoyaltyCardAdd/<int:pk1>/',
         views.member_loyalty_card_add,
         name='member_loyalty_card_add'),
    path('TI_Management_app/<int:pk>/editLoyaltyCardEdit/<int:pk1>/',
         views.member_loyalty_card_edit,
         name='member_loyalty_card_edit'),
    path('TI_Management_app/<int:pk>/editLoyaltyCardIDEdit/<int:pk1>/',
         views.member_loyalty_card_id_edit,
         name='member_loyalty_card_id_edit'),
    path('TI_Management_app/<int:pk>/editLoyaltyCardDelete/<int:pk1>/',
         views.member_loyalty_card_delete,
         name='member_loyalty_card_delete'),
    path('TI_Management_app/<int:pk>/editMemberGroupAdd/<int:pk1>/',
         views.member_group_add,
         name='member_group_add'),
    path('TI_Management_app/<int:pk>/editGroupDelete/<int:pk1>/',
         views.member_group_delete,
         name='member_group_delete'),
    path('TI_Management_app/<int:pk>/editMemberNotepadAdd/',
         views.member_notepad_add,
         name='member_notepad_add'),
    path('TI_Management_app/<int:pk>/editMemberNotepadEdit/<int:pk1>/',
         views.member_notepad_edit,
         name='member_notepad_edit'),
    path('TI_Management_app/<int:pk>/editMemberNotepadHistory/<str:title>/',
         views.member_notepad_history,
         name='member_notepad_history'),
    path('TI_Management_app/<int:pk>/editMemberNotepadHistoryPDF/<str:title>/',
         views.member_notepad_history_pdf,
         name='member_notepad_history_pdf'),
    path('TI_Management_app/<int:pk>/editMemberNotepadDeleteAll/',
         views.member_notepad_delete_all,
         name='member_notepad_delete_all'),
    path('TI_Management_app/member_search/',
         views.member_search,
         name='member_search'),
    path('TI_Management_app/groups/',
         views.groups_list,
         name='groups_list'),
    path('TI_Management_app/groupDetail/<int:pk>/',
         views.group_detail,
         name='group_detail'),
    path('TI_Management_app/groupDetail/<int:pk>/editFile/',
         views.group_file_edit,
         name='group_file_edit'),
    path('TI_Management_app/groupDetail/<int:pk>/deleteFile/<int:pk1>/',
         views.group_file_delete,
         name='group_file_delete'),
    path('TI_Management_app/groupMemberSearch/<int:pk>/',
         views.group_member_search,
         name='group_member_search'),
    path('TI_Management_app/groupsAdd/',
         views.groups_add,
         name='groups_add'),
    path('TI_Management_app/groupEdit/<int:pk>',
         views.groups_edit,
         name='groups_edit'),
    path('TI_Management_app/groupAddMember/<int:pk>/<int:pk1>/',
         views.group_add_member,
         name='group_add_member'),
    path('TI_Management_app/groupDelete/<int:pk>/',
         views.group_delete_all,
         name='group_delete_all'),
    path('TI_Management_app/groupDetail/<int:pk>/groupDeleteMember/<int:pk1>',
         views.group_delete_member,
         name='group_delete_member'),
    path('TI_Management_app/groupSearch/',
         views.group_search,
         name='group_search'),
    path('TI_Management_app/loyaltyCardsList/',
         views.loyalty_card_list,
         name='loyalty_card_list'),
    path('TI_Management_app/loyaltyCardsDetail/<int:pk>/',
         views.loyalty_card_detail,
         name='loyalty_card_detail'),
    path('TI_Management_app/loyaltyCardsAdd/',
         views.loyalty_card_add,
         name='loyalty_card_add'),
    path('TI_Management_app/loyaltyCardsEdit/<int:pk>',
         views.loyalty_card_edit,
         name='loyalty_card_edit'),
    path('TI_Management_app/loyaltyCardsAddMember/<int:pk>/<int:pk1>/',
         views.loyalty_card_add_member,
         name='loyalty_card_add_member'),
    path('TI_Management_app/loyaltyCardsDetail/<int:pk>/loyaltyCardsDeleteMember/<int:pk1>',
         views.loyalty_card_delete_member,
         name='loyalty_card_delete_member'),
    path('TI_Management_app/loyaltyCardsDeleteDelete/<int:pk>/',
         views.loyalty_card_delete_all,
         name='loyalty_card_delete_all'),
    # path('TI_Management_app/loyaltyCardsExportAllUsers/<int:pk>/<str:separator>/',
    # path('TI_Management_app/loyaltyCardsExportAllUsers/<int:pk>/',
    #      views.loyalty_cards_export_all_users,
    #      name='loyalty_cards_export_all_users'),
    # path('TI_Management_app/loyaltyCardsExportToBePickedUp/<int:pk>/',
    #      views.loyalty_cards_export_to_be_picked_up,
    #      name='loyalty_cards_export_to_be_picked_up'),
    # path('TI_Management_app/loyaltyCardsExportOrdered/<int:pk>/',
    #      views.loyalty_cards_export_ordered,
    #      name='loyalty_cards_export_ordered'),
    # path('TI_Management_app/loyaltyCardsExportToOrder/<int:pk>/',
    #      views.loyalty_cards_export_to_order,
    #      name='loyalty_cards_export_to_order'),
    # path('TI_Management_app/loyaltyCardsExportDeactivated/<int:pk>/',
    #      views.loyalty_cards_export_deactivated,
    #      name='loyalty_cards_export_deactivated'),
    path('TI_Management_app/loyaltyCardsAddFileOrder/<int:pk>/',
         views.loyalty_cards_add_file_order,
         name='loyalty_cards_add_file_order'),
    path('TI_Management_app/loyaltyCardsAddFileToBePickedUp/<int:pk>/',
         views.loyalty_cards_add_file_to_be_picked_up,
         name='loyalty_cards_add_file_to_be_picked_up'),
    path('TI_Management_app/loyaltyCardsAddMemberFileOrder/<int:pk>/',
         views.loyalty_cards_add_member_file_order,
         name='loyalty_cards_add_member_file_order'),
    path('TI_Management_app/loyaltyCardsAddMemberFileOrderSearch/<int:pk>/',
         views.loyalty_card_member_file_order_search,
         name='loyalty_card_member_file_order_search'),
    path('TI_Management_app/loyaltyCardsAddMemberFileToBePickedUp/<int:pk>/',
         views.loyalty_cards_add_member_file_to_be_picked_up,
         name='loyalty_cards_add_member_file_to_be_picked_up'),
    path('TI_Management_app/loyaltyCardsAddMemberFileToBePickedUpSearch/<int:pk>/',
         views.loyalty_card_member_file_to_be_picked_up_search,
         name='loyalty_card_member_file_to_be_picked_up_search'),
    path('TI_Management_app/loyaltyCardsMemberSearch/<int:pk>/',
         views.loyalty_card_member_search,
         name='loyalty_card_member_search'),
    path('TI_Management_app/loyaltyCardsSearch/',
         views.loyalty_card_search,
         name='loyalty_card_search'),

]
